"""`paperdb config / init / workspace / start` — configuration / lifecycle commands.

These don't touch the DB (init creates the workspace directory; start spawns
subprocesses), so they're invoked before the `with DatabaseConnection` block.
"""

from __future__ import annotations

import json
import os as _os
import sys
from pathlib import Path
from pathlib import Path as _Path


_CONFIG_TEMPLATE = '''\
# paperdb configuration
# Generated by `paperdb config init`. Edit and save.
#
# Real environment variables (LLM_API_KEY etc.) always override values here.
# File permission is 0600 (owner read/write only) — your API keys stay private.

[paths]
# Override default data directory (auto-derived from OS conventions otherwise).
# data_dir = "~/Library/Application Support/paperdb"
# db_path  = "~/Library/Application Support/paperdb/papers.db"
# pdf_dir  = "~/Library/Application Support/paperdb/pdfs"

[runtime]
# verbose = false

[llm]
# REQUIRED if you want LLM features (analyze / embed / agent / search rerank).
provider = "deepseek"
api_key = ""                    # ← paste your DeepSeek API key here
embedding_api_key = ""          # ← paste your DashScope (Qwen) API key here

# Optional — defaults shown commented out
# base_url = "https://api.deepseek.com/v1"
# complex_model = "deepseek-v4-pro"        # complex tier (thinking ON)
# simple_model  = "deepseek-v4-flash"      # simple tier (thinking OFF)
# complex_thinking = "enabled"
# simple_thinking  = "disabled"
# complex_reasoning_effort = "high"        # "high" | "max"

# Embedding (Qwen) — defaults route to DashScope International
# embedding_model = "text-embedding-v4"
# embedding_base_url = "https://dashscope-intl.aliyuncs.com/compatible-mode/v1"
# embedding_dimensions = 1024              # 64 | 128 | 256 | 512 | 768 | 1024 | 1536 | 2048
# embedding_batch_size = 10                # Qwen v4 caps at 10

# Per-agent tier routing (which agent uses complex vs simple)
# tier_analyze_paper = "complex"
# tier_score_refs    = "simple"
# tier_lit_review    = "complex"
# tier_rerank        = "simple"
'''


def cmd_config(args, db=None) -> None:
    from config import default_config_path

    action = getattr(args, "config_action", None)

    if action == "path":
        print(default_config_path())
        return

    if action == "init":
        path = _Path(args.path) if args.path else default_config_path()
        if path.exists() and not args.force:
            print(f"Config file already exists: {path}", file=sys.stderr)
            print("Use --force to overwrite, or edit it directly.", file=sys.stderr)
            sys.exit(1)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(_CONFIG_TEMPLATE, encoding="utf-8")
        try:
            path.chmod(0o600)
        except Exception:
            pass  # Windows / non-POSIX
        print(f"Wrote template config to:  {path}")
        print()
        print("Next steps:")
        print(f"  1. Open in your editor:    open '{path}'   (or use vim/nano/etc.)")
        print("  2. Fill in api_key and embedding_api_key")
        print("  3. Save the file")
        print("  4. Verify with:            paperdb config show")
        print("  5. Launch the app:         paperdb start")
        return

    if action == "show":
        from config import get_config, get_env_vars_from_config_file, resolve_workspace
        ws, ws_source = resolve_workspace()
        cfg = get_config()
        path = cfg.config_file_path()
        injected = get_env_vars_from_config_file()
        print("══════════════════════════════════════════════════════════════════")
        print(f"  Active workspace : {ws}")
        print(f"                     (source: {ws_source})")
        print(f"  Config file      : {path}")
        print(f"                     {'(exists)' if path.is_file() else '(MISSING — run: paperdb init)'}")
        print("══════════════════════════════════════════════════════════════════")
        print(f"Database         : {cfg.db_path}")
        print(f"PDF dir          : {cfg.pdf_dir}")
        print(f"Archive dir      : {cfg.archive_dir}")
        print(f"Cache dir        : {cfg.cache_dir}")
        print()
        print("LLM environment (after config file applied):")
        sensitive = {"LLM_API_KEY", "LLM_EMBEDDING_API_KEY"}
        env_keys = [
            "LLM_PROVIDER", "LLM_BASE_URL",
            "LLM_API_KEY", "LLM_EMBEDDING_API_KEY",
            "LLM_COMPLEX_MODEL", "LLM_SIMPLE_MODEL",
            "LLM_COMPLEX_THINKING", "LLM_SIMPLE_THINKING",
            "LLM_COMPLEX_REASONING_EFFORT",
            "LLM_EMBEDDING_MODEL", "LLM_EMBEDDING_DIMENSIONS",
        ]
        for k in env_keys:
            v = _os.environ.get(k, "")
            tag = "(from config file)" if k in injected else (
                "(from real env)" if v else ""
            )
            display = v
            if k in sensitive and v:
                display = v[:6] + "…" + v[-4:] if len(v) > 12 else "(set)"
            print(f"  {k:<32} = {display or '(unset)'}  {tag}")
        return

    print("Usage: paperdb config {init|show|path}", file=sys.stderr)
    sys.exit(1)


def cmd_start(args, db=None) -> None:
    """Launch paperdb-api + paperdb-ui together. Ctrl-C kills both."""
    import shutil
    import signal
    import socket
    import subprocess
    import time

    api_exe = shutil.which("paperdb-api")
    ui_exe = shutil.which("paperdb-ui") if not args.no_ui else None
    if api_exe is None:
        api_cmd = [sys.executable, "-m", "paperdb_api.server"]
    else:
        api_cmd = [api_exe]
    api_cmd += ["--host", args.host, "--port", str(args.api_port)]

    if not args.no_ui:
        if ui_exe is None:
            ui_cmd = [sys.executable, "-m", "paperdb_ui.launcher"]
        else:
            ui_cmd = [ui_exe]
        ui_cmd += ["--host", args.host, "--port", str(args.ui_port),
                    "--api-url", f"http://localhost:{args.api_port}"]
    else:
        ui_cmd = None

    print(f"Starting paperdb-api on {args.host}:{args.api_port} ...")
    api_proc = subprocess.Popen(api_cmd)

    ok = False
    for _ in range(40):
        if api_proc.poll() is not None:
            print(f"\nAPI process exited prematurely (code {api_proc.returncode}). "
                   "Check the logs above.", file=sys.stderr)
            sys.exit(1)
        try:
            with socket.create_connection(("localhost", args.api_port), timeout=0.4):
                ok = True
                break
        except OSError:
            time.sleep(0.5)
    if not ok:
        api_proc.terminate()
        print("\nAPI did not start within 20s. Aborting.", file=sys.stderr)
        sys.exit(1)
    print("✓ API is up.")

    ui_proc = None
    if ui_cmd is not None:
        print(f"Starting paperdb-ui on {args.host}:{args.ui_port} ...")
        ui_proc = subprocess.Popen(ui_cmd)
        print(f"\nOpen in browser:  http://localhost:{args.ui_port}\n")
    else:
        print(f"\nAPI ready at:     http://localhost:{args.api_port}\n")

    stop = {"flag": False}

    def handle_sigint(signum, frame):
        if stop["flag"]:
            return
        stop["flag"] = True
        print("\nShutting down ...")
        for proc in (ui_proc, api_proc):
            if proc and proc.poll() is None:
                proc.terminate()

    signal.signal(signal.SIGINT, handle_sigint)
    signal.signal(signal.SIGTERM, handle_sigint)

    try:
        while True:
            time.sleep(0.5)
            if api_proc.poll() is not None:
                print(f"\nAPI exited (code {api_proc.returncode}). Stopping UI.",
                      file=sys.stderr)
                if ui_proc and ui_proc.poll() is None:
                    ui_proc.terminate()
                break
            if ui_proc is not None and ui_proc.poll() is not None:
                print(f"\nUI exited (code {ui_proc.returncode}). Stopping API.",
                      file=sys.stderr)
                api_proc.terminate()
                break
    finally:
        for proc in (ui_proc, api_proc):
            if proc and proc.poll() is None:
                try:
                    proc.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    proc.kill()
        print("Done.")


def cmd_init(args, db=None) -> None:
    """Bootstrap a new paperdb workspace."""
    from workspace_ops import init_workspace
    from config import default_workspace_dir

    target = Path(args.path).expanduser() if args.path else default_workspace_dir()
    print(f"Initializing paperdb workspace at: {target}\n")
    result = init_workspace(target, overwrite_config=args.force_config)
    cfg_path = result["config_path"]
    print(f"\n✓ Workspace ready: {target}")
    print(f"  Next steps:")
    print(f"    1. Edit {cfg_path}  and paste your API keys")
    print(f"    2. paperdb ingest path/to/paper.pdf")
    print(f"    3. paperdb start                 # launches API + Streamlit UI")
    print(f"\nTo use this workspace by default in a different shell, run:")
    print(f"    export PAPERDB_WORKSPACE={target}")


def cmd_workspace(args, db=None) -> None:
    """Inspect or migrate the workspace."""
    if args.workspace_action == "show":
        from workspace_ops import inspect_workspace
        info = inspect_workspace()
        if getattr(args, "as_json", False):
            print(json.dumps(info, indent=2, ensure_ascii=False))
            return
        print(f"Workspace : {info['workspace']}  (source: {info['workspace_source']})")
        print(f"Config    : {info['config_file']}  (source: {info['config_source']})")
        print(f"\nLayout:")
        for k, exists in info["exists"].items():
            mark = "✓" if exists else "·"
            print(f"  {mark}  {k}")
        if "db_size_bytes" in info:
            mb = info["db_size_bytes"] / 1024 / 1024
            print(f"\npapers.db: {mb:.1f} MB")
        if info["legacy_detected"]:
            print(f"\n⚠ Legacy data found in old OS directories:")
            for kind, p in info["legacy_detected"].items():
                print(f"    {kind:>8}: {p}")
            print(f"  Run `paperdb workspace migrate` to consolidate.")
        return

    if args.workspace_action == "migrate":
        from workspace_ops import execute_migration, plan_migration
        from config import default_workspace_dir

        target = Path(args.to).expanduser() if args.to else default_workspace_dir()
        plan = plan_migration(target)
        if plan.is_empty():
            print(f"No legacy data found — nothing to migrate.")
            print(f"(checked legacy OS paths; workspace target was {target})")
            return

        print(plan.summary())
        print()

        if args.dry_run:
            print("(--dry-run: no files moved)")
            return

        if not args.yes:
            reply = input(f"Proceed with migration? [y/N]: ").strip().lower()
            if reply not in ("y", "yes"):
                print("Aborted.")
                return

        execute_migration(plan, archive_old=not args.no_archive)
        return

    print("Usage: paperdb workspace {show|migrate}")
    sys.exit(2)
